### ISSUE TITLE
Any reason to require personal access token?

### ISSUE THREAD

**Issue by vsoch** [DataDrake/cuppa#18]
hey @DataDrake ! I'm trying this for the first time and it's a great idea, but I have a quick question. The responses that I get are basically 404 when I don't have an access token, even for public repos. 
```
2020/10/03 10:17:44 Unable to find cuppa https://github.com/DataDrake/cuppa/archive/v1.1.0.tar.gz
```
but I've used the GitHub API before, and although the limit is lower, it should work without a token. What am I doing wrong?

**Comment by DataDrake** [comment]
As already discussed, the token is required for the v4 GraphQL API. I do not support fallback for the v3 API as it is too "chatty" for large numbers of queries (which I do often). It's also worth using the GraphQL API because an entire require is only one credit, whereas on the v3 API, I was routinely running out of credits, due to needing multiple requests per source.

**Comment by vsoch** [comment]
Thanks for answering the question! I’m a new user so “as already discussed” doesn’t give me much context. But I can sense that you are possibly annoyed by the question, so thank you for repeating the answer for me.

**Comment by DataDrake** [comment]
@vsoch This was already discussed and explained in alecbcs/lookout#3. You and @alecbcs came to the correct conclusion about the GraphQL API requiring a token before I even saw this issue had been opened. I merely provided context as to why I chose the v4 API over the v3 API in the first place.

**Comment by vsoch** [comment]
Yes, we were looking for clarification! I missed the context that "as already discussed" was referring to our speculation. Thanks again!
